spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/claimhelpers
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  ai:
    openai:
      api-key:
      embedding:
        options:
          # text-embedding-ada-002: 1536차원
          model: text-embedding-ada-002
    anthropic:
      api-key:
    vectorstore:
      pgvector:
        dimensions: 1536
        index-type: hnsw
        distance-type: cosine_distance